package trading.eligibility.regulatory.CFTC.USPerson

import com.sapient.mapreduce.example.model.RegulatoryTradeEligibilityRequest;

rule "Customer is a US Person"
when
   $request : RegulatoryTradeEligibilityRequest( ruleResultsMap.get("US Person") == null )
   RegulatoryTradeEligibilityRequest( ruleResultsMap.get("isValid") == "TRUE")
   RegulatoryTradeEligibilityRequest( customer.principalPlaceOfBusiness == "US")
then
   $request.getRuleResultsMap().put("US Person","TRUE");
end

rule "Customer is not a US Person"
when
   $request : RegulatoryTradeEligibilityRequest( ruleResultsMap.get("US Person") == null )
   RegulatoryTradeEligibilityRequest( ruleResultsMap.get("isValid") == "TRUE")
   RegulatoryTradeEligibilityRequest( customer.principalPlaceOfBusiness != "US")
then
   $request.getRuleResultsMap().put("US Person","FALSE");
end
